export const env = {
  // Empty string = same-origin (via Next.js rewrites in next.config.mjs)
  apiUrl: process.env.NEXT_PUBLIC_API_URL ?? "",
  appUrl: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
  midtransClientKey: process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY ?? "",
  midtransIsProduction: process.env.NEXT_PUBLIC_MIDTRANS_IS_PRODUCTION === "true",
} as const;

export const apiPaths = {
  csrfCookie: "/sanctum/csrf-cookie",
  auth: {
    register: "/api/v1/auth/register",
    login: "/api/v1/auth/login",
    logout: "/api/v1/auth/logout",
    me: "/api/v1/auth/me",
    forgotPassword: "/api/v1/auth/forgot-password",
    resetPassword: "/api/v1/auth/reset-password",
    verificationNotice: "/api/v1/auth/email/verification-notification",
    resendVerification: "/api/v1/auth/email/resend-verification",
    verifyEmail: (id: string, hash: string) => `/api/v1/auth/email/verify/${id}/${hash}`,
    organizers: "/api/v1/auth/organizers",
    switchOrganizer: "/api/v1/auth/organizer/switch",
    organizerInvitations: "/api/v1/auth/organizer-invitations",
    acceptOrganizerInvitation: (memberId: number) =>
      `/api/v1/auth/organizer-invitations/${memberId}/accept`,
    declineOrganizerInvitation: (memberId: number) =>
      `/api/v1/auth/organizer-invitations/${memberId}/decline`,
    tokens: "/api/v1/auth/tokens",
    tokensCurrent: "/api/v1/auth/tokens/current",
  },
  events: {
    list: "/api/v1/events",
    create: "/api/v1/events",
    show: (uuid: string) => `/api/v1/events/${uuid}`,
    update: (uuid: string) => `/api/v1/events/${uuid}`,
    delete: (uuid: string) => `/api/v1/events/${uuid}`,
    publish: (uuid: string) => `/api/v1/events/${uuid}/publish`,
    draft: (uuid: string) => `/api/v1/events/${uuid}/draft`,
    adminList: "/api/v1/admin/events",
    publicList: "/api/v1/public/events",
    publicShow: (uuid: string) => `/api/v1/public/events/${uuid}`,
    publicCategories: "/api/v1/public/event-categories",
    publicCities: "/api/v1/public/cities",
    publicStats: "/api/v1/public/stats",
    publicFeaturedOrganizers: "/api/v1/public/featured-organizers",
  },
  venues: {
    list: "/api/v1/venues",
    create: "/api/v1/venues",
  },
  eventCategories: "/api/v1/event-categories",
  ticketTypes: {
    list: (eventUuid: string) => `/api/v1/events/${eventUuid}/ticket-types`,
    create: (eventUuid: string) => `/api/v1/events/${eventUuid}/ticket-types`,
    show: (eventUuid: string, ticketTypeId: number) =>
      `/api/v1/events/${eventUuid}/ticket-types/${ticketTypeId}`,
    update: (eventUuid: string, ticketTypeId: number) =>
      `/api/v1/events/${eventUuid}/ticket-types/${ticketTypeId}`,
    delete: (eventUuid: string, ticketTypeId: number) =>
      `/api/v1/events/${eventUuid}/ticket-types/${ticketTypeId}`,
    publicList: (eventUuid: string) => `/api/v1/public/events/${eventUuid}/ticket-types`,
  },
  organizers: {
    create: "/api/v1/organizers",
    dashboardSummary: "/api/v1/organizers/current/dashboard/summary",
    dashboardTrends: "/api/v1/organizers/current/dashboard/trends",
    dashboardInsights: "/api/v1/organizers/current/dashboard/insights",
    dashboardScannerSummary: "/api/v1/organizers/current/dashboard/scanner-summary",
    members: "/api/v1/organizers/current/members",
    member: (memberId: number) => `/api/v1/organizers/current/members/${memberId}`,
    adminList: "/api/v1/admin/organizers",
    adminPending: "/api/v1/admin/organizers/pending",
    adminShow: (uuid: string) => `/api/v1/admin/organizers/${uuid}`,
    adminApprove: (uuid: string) => `/api/v1/admin/organizers/${uuid}/approve`,
    adminReject: (uuid: string) => `/api/v1/admin/organizers/${uuid}/reject`,
    adminSuspend: (uuid: string) => `/api/v1/admin/organizers/${uuid}/suspend`,
    adminActivate: (uuid: string) => `/api/v1/admin/organizers/${uuid}/activate`,
  },
  checkout: {
    create: (eventUuid: string) => `/api/v1/public/events/${eventUuid}/checkout`,
    listOrders: "/api/v1/public/orders",
    showOrder: (uuid: string) => `/api/v1/public/orders/${uuid}`,
    validatePayment: (uuid: string) => `/api/v1/public/orders/${uuid}/validate-payment`,
  },
  checkIn: {
    gates: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/gates`,
    verify: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/verify`,
    scan: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/scan`,
    manual: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/manual`,
    list: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins`,
    stats: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/stats`,
    ticketQr: (ticketUuid: string) => `/api/v1/tickets/${ticketUuid}/qr`,
  },
  admin: {
    settings: "/api/v1/admin/settings",
    setting: (key: string) => `/api/v1/admin/settings/${key}`,
    dashboardSummary: "/api/v1/admin/dashboard/summary",
    analyticsTrends: "/api/v1/admin/analytics/trends",
    activityLogs: "/api/v1/admin/activity-logs",
    auditLogs: "/api/v1/admin/audit-logs",
    organizerFeeConfigs: (uuid: string) => `/api/v1/admin/organizers/${uuid}/fee-configs`,
    organizerFeeConfig: (uuid: string, id: number) =>
      `/api/v1/admin/organizers/${uuid}/fee-configs/${id}`,
  },
} as const;

export const routes = {
  home: "/",
  publicEvent: (uuid: string) => `/events/${uuid}`,
  publicEventCheckout: (uuid: string, ticketTypeId: number) =>
    `/events/${uuid}/checkout?ticket=${ticketTypeId}`,
  checkoutFinish: (orderUuid: string) => `/checkout/${orderUuid}/finish`,
  myTickets: "/my/tickets",
  myTransactions: "/my/transactions",
  login: "/login",
  loginWithRedirect: (redirect: string) =>
    `/login?redirect=${encodeURIComponent(redirect)}`,
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  verifyEmailConfirm: "/verify-email/confirm",
  verifyEmailPending: "/verify-email/pending",
  selectOrganizer: "/select-organizer",
  createOrganizer: "/create-organizer",
  organizerDashboard: "/dashboard",
  organizerAnalytics: "/analytics",
  organizerTeam: "/team",
  organizerEvents: "/events",
  organizerEventNew: "/events/new",
  organizerEventEdit: (uuid: string) => `/events/${uuid}/edit`,
  organizerEventTickets: (uuid: string) => `/events/${uuid}/tickets`,
  organizerEventTicketNew: (uuid: string) => `/events/${uuid}/tickets/new`,
  organizerEventTicketEdit: (eventUuid: string, ticketId: number) =>
    `/events/${eventUuid}/tickets/${ticketId}/edit`,
  adminDashboard: "/admin/dashboard",
  adminEvents: "/admin/events",
  adminOrganizers: "/admin/organizers",
  adminOrganizerDetail: (uuid: string) => `/admin/organizers/${uuid}`,
  adminSettings: "/admin/settings",
  adminAnalytics: "/admin/analytics",
  adminLogs: "/admin/logs",
  scanner: "/scan",
  organizerEventAttendance: (uuid: string) => `/events/${uuid}/attendance`,
} as const;

export const roleRoutes: Record<string, string> = {
  super_admin: routes.adminDashboard,
  organizer: routes.organizerDashboard,
  staff: routes.organizerDashboard,
  participant: routes.home,
};
