export const env = {
  // Empty string = same-origin (via Next.js rewrites in next.config.mjs)
  apiUrl: process.env.NEXT_PUBLIC_API_URL ?? "",
  appUrl: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
  midtransClientKey: process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY ?? "",
  midtransIsProduction: process.env.NEXT_PUBLIC_MIDTRANS_IS_PRODUCTION === "true",
} as const;

export const apiPaths = {
  csrfCookie: "/sanctum/csrf-cookie",
  auth: {
    register: "/api/v1/auth/register",
    login: "/api/v1/auth/login",
    logout: "/api/v1/auth/logout",
    me: "/api/v1/auth/me",
    forgotPassword: "/api/v1/auth/forgot-password",
    resetPassword: "/api/v1/auth/reset-password",
    verificationNotice: "/api/v1/auth/email/verification-notification",
    resendVerification: "/api/v1/auth/email/resend-verification",
    verifyEmail: (id: string, hash: string) => `/api/v1/auth/email/verify/${id}/${hash}`,
    organizers: "/api/v1/auth/organizers",
    switchOrganizer: "/api/v1/auth/organizer/switch",
    organizerInvitations: "/api/v1/auth/organizer-invitations",
    acceptOrganizerInvitation: (memberId: number) =>
      `/api/v1/auth/organizer-invitations/${memberId}/accept`,
    declineOrganizerInvitation: (memberId: number) =>
      `/api/v1/auth/organizer-invitations/${memberId}/decline`,
    tokens: "/api/v1/auth/tokens",
    tokensCurrent: "/api/v1/auth/tokens/current",
  },
  events: {
    list: "/api/v1/events",
    create: "/api/v1/events",
    show: (uuid: string) => `/api/v1/events/${uuid}`,
    update: (uuid: string) => `/api/v1/events/${uuid}`,
    delete: (uuid: string) => `/api/v1/events/${uuid}`,
    publish: (uuid: string) => `/api/v1/events/${uuid}/publish`,
    draft: (uuid: string) => `/api/v1/events/${uuid}/draft`,
    dashboardSummary: (uuid: string) => `/api/v1/events/${uuid}/dashboard/summary`,
    dashboardTrends: (uuid: string) => `/api/v1/events/${uuid}/dashboard/trends`,
    dashboardInsights: (uuid: string) => `/api/v1/events/${uuid}/dashboard/insights`,
    attendees: (uuid: string) => `/api/v1/events/${uuid}/attendees`,
    orderShow: (uuid: string, orderUuid: string) => `/api/v1/events/${uuid}/orders/${orderUuid}`,
    bannerUpload: "/api/v1/events/banner-upload",
    adminList: "/api/v1/admin/events",
    publicList: "/api/v1/public/events",
    publicShow: (uuid: string) => `/api/v1/public/events/${uuid}`,
    publicCategories: "/api/v1/public/event-categories",
    publicCities: "/api/v1/public/cities",
    publicStats: "/api/v1/public/stats",
    publicFeaturedOrganizers: "/api/v1/public/featured-organizers",
    publicCreator: (slug: string) => `/api/v1/public/creators/${slug}`,
  },
  venues: {
    list: "/api/v1/venues",
    create: "/api/v1/venues",
  },
  eventCategories: "/api/v1/event-categories",
  eventTags: {
    list: "/api/v1/event-tags",
    create: "/api/v1/event-tags",
  },
  registrationForms: {
    show: (eventUuid: string) => `/api/v1/events/${eventUuid}/registration-form`,
    sync: (eventUuid: string) => `/api/v1/events/${eventUuid}/registration-form/fields`,
    publicShow: (eventUuid: string) => `/api/v1/public/events/${eventUuid}/registration-form`,
  },
  ticketTypes: {
    list: (eventUuid: string) => `/api/v1/events/${eventUuid}/ticket-types`,
    create: (eventUuid: string) => `/api/v1/events/${eventUuid}/ticket-types`,
    show: (eventUuid: string, ticketTypeId: number) =>
      `/api/v1/events/${eventUuid}/ticket-types/${ticketTypeId}`,
    update: (eventUuid: string, ticketTypeId: number) =>
      `/api/v1/events/${eventUuid}/ticket-types/${ticketTypeId}`,
    delete: (eventUuid: string, ticketTypeId: number) =>
      `/api/v1/events/${eventUuid}/ticket-types/${ticketTypeId}`,
    publicList: (eventUuid: string) => `/api/v1/public/events/${eventUuid}/ticket-types`,
  },
  organizers: {
    create: "/api/v1/organizers",
    current: "/api/v1/organizers/current",
    complianceShow: "/api/v1/organizers/current/compliance",
    complianceSubmit: "/api/v1/organizers/current/compliance",
    complianceVerify: (uuid: string) => `/api/v1/admin/organizers/${uuid}/compliance/verify`,
    complianceReject: (uuid: string) => `/api/v1/admin/organizers/${uuid}/compliance/reject`,
    dashboardSummary: "/api/v1/organizers/current/dashboard/summary",
    dashboardTrends: "/api/v1/organizers/current/dashboard/trends",
    dashboardInsights: "/api/v1/organizers/current/dashboard/insights",
    dashboardScannerSummary: "/api/v1/organizers/current/dashboard/scanner-summary",
    feePreview: "/api/v1/organizers/current/fee-preview",
    members: "/api/v1/organizers/current/members",
    member: (memberId: number) => `/api/v1/organizers/current/members/${memberId}`,
    adminList: "/api/v1/admin/organizers",
    adminPending: "/api/v1/admin/organizers/pending",
    adminShow: (uuid: string) => `/api/v1/admin/organizers/${uuid}`,
    adminApprove: (uuid: string) => `/api/v1/admin/organizers/${uuid}/approve`,
    adminReject: (uuid: string) => `/api/v1/admin/organizers/${uuid}/reject`,
    adminSuspend: (uuid: string) => `/api/v1/admin/organizers/${uuid}/suspend`,
    adminActivate: (uuid: string) => `/api/v1/admin/organizers/${uuid}/activate`,
  },
  checkout: {
    create: (eventUuid: string) => `/api/v1/public/events/${eventUuid}/checkout`,
    quote: (eventUuid: string) => `/api/v1/public/events/${eventUuid}/checkout/quote`,
    listOrders: "/api/v1/public/orders",
    showOrder: (uuid: string) => `/api/v1/public/orders/${uuid}`,
    validatePayment: (uuid: string) => `/api/v1/public/orders/${uuid}/validate-payment`,
  },
  checkIn: {
    gates: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/gates`,
    verify: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/verify`,
    scan: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/scan`,
    manual: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/manual`,
    list: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins`,
    stats: (eventUuid: string) => `/api/v1/events/${eventUuid}/check-ins/stats`,
    ticketQr: (ticketUuid: string) => `/api/v1/tickets/${ticketUuid}/qr`,
  },
  admin: {
    settings: "/api/v1/admin/settings",
    setting: (key: string) => `/api/v1/admin/settings/${key}`,
    dashboardSummary: "/api/v1/admin/dashboard/summary",
    analyticsTrends: "/api/v1/admin/analytics/trends",
    activityLogs: "/api/v1/admin/activity-logs",
    auditLogs: "/api/v1/admin/audit-logs",
    organizerFeeConfigs: (uuid: string) => `/api/v1/admin/organizers/${uuid}/fee-configs`,
    organizerFeeConfig: (uuid: string, id: number) =>
      `/api/v1/admin/organizers/${uuid}/fee-configs/${id}`,
  },
} as const;

export const routes = {
  home: "/",
  about: "/tentang-kami",
  terms: "/syarat-ketentuan",
  privacy: "/kebijakan-privasi",
  faq: "/faq",
  pricing: "/biaya",
  buatEvent: "/buat-event",
  profile: "/profile",
  publicEvent: (uuid: string) => `/events/${uuid}`,
  publicCreator: (slug: string) => `/creator/${slug}`,
  publicEventCheckout: (uuid: string, ticketTypeId: number, qty = 1) => {
    const params = new URLSearchParams({ ticket: String(ticketTypeId) });
    if (qty > 1) {
      params.set("qty", String(qty));
    }
    return `/events/${uuid}/checkout?${params.toString()}`;
  },
  checkoutFinish: (orderUuid: string) => `/checkout/${orderUuid}/finish`,
  myTickets: "/my/tickets",
  myTransactions: "/my/transactions",
  login: "/login",
  loginWithRedirect: (redirect: string) =>
    `/login?redirect=${encodeURIComponent(redirect)}`,
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  verifyEmailConfirm: "/verify-email/confirm",
  verifyEmailPending: "/verify-email/pending",
  selectOrganizer: "/select-organizer",
  createOrganizer: "/create-organizer",
  organizerDashboard: "/dashboard",
  organizerAnalytics: "/analytics",
  organizerTeam: "/team",
  organizerCompliance: "/compliance",
  organizerEvents: "/events",
  organizerEventNew: "/events/new",
  organizerEventEdit: (uuid: string) => `/events/${uuid}/edit`,
  organizerEventDashboard: (uuid: string) => `/events/${uuid}/dashboard`,
  organizerEventTickets: (uuid: string) => `/events/${uuid}/tickets`,
  organizerEventRegistration: (uuid: string) => `/events/${uuid}/registration`,
  organizerEventCheckoutSettings: (uuid: string) => `/events/${uuid}/checkout-settings`,
  organizerEventAttendees: (uuid: string) => `/events/${uuid}/attendees`,
  organizerEventMicrosite: (uuid: string) => `/events/${uuid}/microsite`,
  organizerEventTicketNew: (uuid: string) => `/events/${uuid}/tickets/new`,
  organizerEventTicketEdit: (eventUuid: string, ticketId: number) =>
    `/events/${eventUuid}/tickets/${ticketId}/edit`,
  adminDashboard: "/admin/dashboard",
  adminEvents: "/admin/events",
  adminOrganizers: "/admin/organizers",
  adminOrganizerDetail: (uuid: string) => `/admin/organizers/${uuid}`,
  adminSettings: "/admin/settings",
  adminAnalytics: "/admin/analytics",
  adminLogs: "/admin/logs",
  scanner: "/scan",
  organizerEventAttendance: (uuid: string) => `/events/${uuid}/attendance`,
} as const;

export const roleRoutes: Record<string, string> = {
  super_admin: routes.adminDashboard,
  organizer: routes.organizerDashboard,
  staff: routes.organizerDashboard,
  participant: routes.home,
};
